#!/usr/bin/env sh

# Concat the trigger together to make it easier to
# track this script itself
TRIG0="no"
TRIG0+="checkin"

TRIG1="auto"
TRIG1+="fix"

# Check for trigger words in staged changes
if git diff --cached | grep '^+' | grep -q -i "${TRIG0}"; then
    echo "Commit rejected: '${TRIG0}' found in staged changes."
    exit 1
fi

if git diff --cached | grep '^+' | grep -q -i "${TRIG1}"; then
    echo "Commit rejected: '${TRIG1}' found in staged changes."
    exit 1
fi

exit 0
